# Generated by Django 3.2.16 on 2022-12-21 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=70, verbose_name='Текст рассылки')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Время запуска рассылки')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Время окончания рассылки')),
                ('code', models.CharField(max_length=3, verbose_name='Код оператора')),
                ('tag', models.CharField(max_length=20, verbose_name='Метка')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='Номер телефона')),
                ('code', models.CharField(max_length=3, verbose_name='Код оператора')),
                ('tag', models.CharField(max_length=20, verbose_name='Метка')),
                ('time_zone', models.IntegerField(default=3, verbose_name='Часовой пояс')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Код оператора')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Метка')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_sent', models.DateTimeField(blank=True, null=True, verbose_name='Время отправки')),
                ('status', models.BooleanField(default=False, verbose_name='Отправлено?')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mass_texting.campaign', verbose_name='Рассылка')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mass_texting.customer', verbose_name='Клиент')),
            ],
        ),
    ]
