# Generated by Django 3.2.16 on 2022-12-21 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mass_texting', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Operator',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
