# Generated by Django 3.2.16 on 2022-12-22 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mass_texting', '0003_alter_customer_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='tag',
            field=models.CharField(blank=True, max_length=20, verbose_name='Метка'),
        ),
    ]
