# Generated by Django 3.2.16 on 2022-12-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mass_texting', '0005_alter_message_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='code',
            field=models.CharField(blank=True, max_length=3, verbose_name='Код оператора'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='tag',
            field=models.CharField(blank=True, max_length=20, verbose_name='Метка'),
        ),
    ]
